version: 2

machine:
  services:
    - docker

jobs:
  test:
    machine: true
    working_directory: ~/lxdhub-web
    steps:
      - checkout
      - run: docker build -t brunnel6/lxdhub-web .
      - run: docker run -it brunnel6/lxdhub-web test

  deploy_docker:
    machine: true
    working_directory: /tmp/lxdhub
    steps:
      - checkout
      - run: ./bin/deploy-docker.sh

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - deploy_docker:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - test


