version: 2

machine:
  services:
    - docker

jobs:
  build:
    machine: true
    working_directory: ~/lxdhub-web
    steps:
      - checkout
      - run: docker build -t brunnerl6/lxdhub-web .
  test:
    docker:
      - image: circleci/node:10-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: yarn install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn run test:ci

  deploy_docker:
    machine: true
    working_directory: /tmp/lxdhub
    steps:
      - checkout
      - run: ./bin/deploy-docker.sh

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test
      - deploy_docker:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - test


